### ISSUE TITLE
Week 3: Map and Lore

### ISSUE THREAD

**Issue by tommyshellberg** [tommyshellberg/unquest-app#49]
- [x] tommyshellberg/unquest-app#41
- [x] tommyshellberg/unquest-app#40
- [x] tommyshellberg/unquest-app#39
- [x] tommyshellberg/unquest-app#38
- [x] tommyshellberg/unquest-app#37
