### ISSUE TITLE
Week 2: Asset Integration & Quest System

### ISSUE THREAD

**Issue by tommyshellberg** [tommyshellberg/unquest-app#50]
- [x] tommyshellberg/unquest-app#42
- [x] tommyshellberg/unquest-app#45
- [x] tommyshellberg/unquest-app#44
- [x] tommyshellberg/unquest-app#43
