### ISSUE TITLE
[EPIC] Create Onboarding Flow

### ISSUE THREAD

**Issue by tommyshellberg** [tommyshellberg/unquest-app#58]
[Refer to Figma](https://www.figma.com/board/F1N2OaPbpyieT2AKambJCK/Unquest-App-Flow?node-id=0-1&p=f&t=x8g67zgL961yjZf5-0) for design/flow.

### Splash page

- [x] tommyshellberg/unquest-app#57
  - [x] name of the app ("unQuest") 
  - [x] short description
  - [x] a "get started" CTA that moves to the Pick a Character page of the Onboarding process.

### Pick a Character Page

- [x] tommyshellberg/unquest-app#56
  - [x] 3 men/3 women - generate an image for each of them along with a name and some kind of personality trait (explorer, wizard, alchemist)
  - [x] Display all 6 with their images and allow them to be selected in the UI
  - [x] Store the selected character for use later.
  - [x] Create a "Continue" CTA that goes to the next step (Screen Time Goal)

### Screen Time Goal

- [x] tommyshellberg/unquest-app#55
  - [x] Use time scrollers like an alarm would use.
  - [x] Ask what their daily goal will be using the same base component.
  - [x] Store both values for re-use later, as the difference between the two will determine how quickly the character will level up (how long the quests will be).

### First Quest

- [x] tommyshellberg/unquest-app#54
- [x] Their first quest will be to take some time away from the phone. Recommendations:
  - [ ] Get a drink of water
  - [ ] Stretch
  - [x] Take a 15 minute walk
- [x] Set the first quest time to 5 minutes so that it's achievable for everyone.
